export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    '__get_candid_interface_tmp_hack' : IDL.Func([], [IDL.Text], ['query']),
    'add_authorized_wasm' : IDL.Func([IDL.Text], [IDL.Text], []),
    'apply_arrangement' : IDL.Func([IDL.Text], [IDL.Text], []),
    'approve_governance_request' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assign_pool_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'canister_browse' : IDL.Func([IDL.Text], [IDL.Text], []),
    'canister_exec' : IDL.Func([IDL.Text], [IDL.Text], []),
    'casals_metadata' : IDL.Func([], [IDL.Text], ['query']),
    'convert_treasury_icp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'create_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'create_section' : IDL.Func([IDL.Text], [IDL.Text], []),
    'create_snapshot' : IDL.Func([IDL.Text], [IDL.Text], []),
    'create_stand' : IDL.Func([IDL.Text], [IDL.Text], []),
    'delete_arrangement' : IDL.Func([IDL.Text], [IDL.Text], []),
    'delete_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'delete_principal_alias' : IDL.Func([IDL.Text], [IDL.Text], []),
    'delete_section' : IDL.Func([IDL.Text], [IDL.Text], []),
    'delete_stand' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deploy_sheet' : IDL.Func([IDL.Text], [IDL.Text], []),
    'destroy_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'destroy_stand' : IDL.Func([IDL.Text], [IDL.Text], []),
    'estimate_deploy' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_arrangement' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_canister_deployment' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_cycle_history' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_cycles' : IDL.Func([], [IDL.Text], []),
    'get_cycles_cached' : IDL.Func([], [IDL.Text], ['query']),
    'get_events' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_orchestration_policies' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_settings' : IDL.Func([], [IDL.Text], ['query']),
    'get_sheet' : IDL.Func([], [IDL.Text], ['query']),
    'get_status' : IDL.Func([], [IDL.Text], ['query']),
    'get_treasury_flow' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'get_tree' : IDL.Func([], [IDL.Text], ['query']),
    'icrc10_supported_standards' : IDL.Func([], [IDL.Text], ['query']),
    'list_arrangements' : IDL.Func([], [IDL.Text], ['query']),
    'list_authorized_wasms' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'list_backend_controllers' : IDL.Func([IDL.Text], [IDL.Text], []),
    'list_governance_requests' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'list_orchestration_actions' : IDL.Func([], [IDL.Text], ['query']),
    'list_permissions' : IDL.Func([], [IDL.Text], ['query']),
    'list_pool' : IDL.Func([], [IDL.Text], ['query']),
    'list_principal_aliases' : IDL.Func([], [IDL.Text], ['query']),
    'list_sections' : IDL.Func([], [IDL.Text], ['query']),
    'list_subnets' : IDL.Func([], [IDL.Text], []),
    'orchestration_configure_baton' : IDL.Func([IDL.Text], [IDL.Text], []),
    'orchestration_execute_action' : IDL.Func([IDL.Text], [IDL.Text], []),
    'orchestration_hand_to_baton' : IDL.Func([IDL.Text], [IDL.Text], []),
    'orchestration_prepare_asset_provision' : IDL.Func(
        [IDL.Text],
        [IDL.Text],
        [],
      ),
    'orchestration_prepare_managed_upgrade' : IDL.Func(
        [IDL.Text],
        [IDL.Text],
        [],
      ),
    'orchestration_refresh' : IDL.Func([IDL.Text], [IDL.Text], []),
    'orchestration_status' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'pool_remove' : IDL.Func([IDL.Text], [IDL.Text], []),
    'provision_assets' : IDL.Func([IDL.Text], [IDL.Text], []),
    'reconcile' : IDL.Func([], [IDL.Text], []),
    'refresh_canisters' : IDL.Func([IDL.Text], [IDL.Text], []),
    'refresh_controllers_cache' : IDL.Func([IDL.Text], [IDL.Text], []),
    'refresh_fx' : IDL.Func([], [IDL.Text], []),
    'refresh_treasury' : IDL.Func([IDL.Text], [IDL.Text], []),
    'register_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'reject_governance_request' : IDL.Func([IDL.Text], [IDL.Text], []),
    'remove_authorized_wasm' : IDL.Func([IDL.Text], [IDL.Text], []),
    'remove_commander' : IDL.Func([IDL.Text], [IDL.Text], []),
    'rename_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'rename_section' : IDL.Func([IDL.Text], [IDL.Text], []),
    'rename_stand' : IDL.Func([IDL.Text], [IDL.Text], []),
    'repair_section' : IDL.Func([IDL.Text], [IDL.Text], []),
    'reset_sheet' : IDL.Func([], [IDL.Text], []),
    'return_cycles' : IDL.Func([IDL.Text], [IDL.Text], []),
    'revert_snapshot' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_active_arrangement' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_arrangement' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_canister_controllers' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_canister_tags' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_commander' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_cycle_policy' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_log_visibility' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_orchestration_policies' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_permissions' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_principal_alias' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_settings' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_sheet' : IDL.Func([IDL.Text], [IDL.Text], []),
    'set_subnet_whitelist' : IDL.Func([IDL.Text], [IDL.Text], []),
    'start_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'stop_canister' : IDL.Func([IDL.Text], [IDL.Text], []),
    'sync_controllers' : IDL.Func([IDL.Text], [IDL.Text], []),
    'top_up' : IDL.Func([IDL.Text], [IDL.Text], []),
    'upgrade_to' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};
export const init = ({ IDL }) => { return []; };
